[package]
name = "framework"
version = "0.1.0"
edition = "2018"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos stdlib"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
clap = "3.1.8"
include_dir = "0.7.2"
log = "0.4.17"
once_cell = "1.10.0"
rayon = "1.5.2"
sha2 = "0.9.3"
siphasher = "0.3.10"
smallvec = "1.8.0"
structopt = "0.3.21"
tempfile = "3.3.0"

aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-types = { path = "../../types" }

move-deps = { path = "../move-deps", features = ["address32"] }
transaction-builder-generator = { path = "../transaction-builder-generator" }

[dev-dependencies]
aptos-vm = { path = "../../aptos-move/aptos-vm" }
move-deps = { path = "../move-deps", features = ["table-extension"] }

[features]
default = []
fuzzing = ["aptos-types/fuzzing"]
